graph TD
    User((User))
    User -- gRPC --> AS[Appointment Service]
    User -- gRPC --> DS[Doctor Service]
    AS -- gRPC --> DS
    AS -- Events --> NATS((NATS Broker))
    DS -- Events --> NATS
    NATS -- Events --> NS[Notification Service]
    AS -- Cache/RateLimit --> Redis[(Redis)]
    DS -- Cache/RateLimit --> Redis
    NS -- Idempotency --> Redis
    NS -- Background Job --> MG[Mock Gateway]
    AS -- DB --> DBA[(Postgres: appt_db)]
    DS -- DB --> DBD[(Postgres: doctor_db)]
