services:
  nats:
    image: nats:latest
    ports:
      - "${NATS_PORT1}:${NATS_PORT1}"
      - "${NATS_PORT2}:${NATS_PORT2}"

  postgres-doctor:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DOCTOR_POSTGRES_DB}
    ports:
      - "${DOCTOR_DB_PORT}:5432"

  postgres-appointment:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${APPOINTMENT_POSTGRES_DB}
    ports:
      - "${APPOINTMENT_DB_PORT}:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
